#!/usr/bin/env python3
"""tool/obsidian_sync.py — 開発資料を Obsidian vault へ自動記録

プロジェクトの資料（設計書・ロードマップ・レポート・プロセス文書）と
git履歴・テスト状況を Obsidian vault に同期する。

使い方:
  python tool/obsidian_sync.py             # 全体同期（docs + index + history）
  python tool/obsidian_sync.py --session "作業内容の要約"   # 作業ログも追加

同期先: C:/Users/ifjvm/Documents/ObsidianAI/projects/ble-encounter-app/
  index.md          … プロジェクト全体のハブ（現況・構成・リンク集）
  history.md        … バージョン履歴（git logから自動生成）
  docs/*.md         … リポジトリ内mdのミラー（frontmatter付与）
  sessions/*.md     … 作業セッションログ（--session時）

設計方針:
- vaultは「読むための場所」。リポジトリのmdを正としてミラーする
- 手書き部分を壊さないため、ミラーは docs/ 配下に限定し index/history は再生成
- wikilinkでノート間を接続し、Obsidianのグラフで辿れるようにする
"""
import re
import subprocess
import sys
from datetime import datetime
from pathlib import Path

sys.stdout.reconfigure(encoding="utf-8", errors="replace")

REPO = Path(__file__).resolve().parent.parent
VAULT = Path(r"C:\Users\ifjvm\Documents\ObsidianAI")
DEST = VAULT / "projects" / "ble-encounter-app"

# リポジトリ内のドキュメント → vault内での表示名
DOCS = {
    "ROADMAP.md": "ロードマップ",
    "REPORT.md": "最新レポート",
    "WORKFLOW.md": "開発ワークフロー",
    "PROMPT_GUIDE.md": "プロンプトガイド",
    "AUTOMATION_PLAN.md": "自動化計画",
    "QA_GUIDE.md": "QAガイド",
    "AUTO_TEST_PLAN.md": "テスト計画",
    "ROADMAP_RECOMMENDATION.md": "ロードマップ推奨",
    "PLAZA_DESIGN.md": "広場育成システム設計",
    "PREFECTURE_PLAN.md": "47都道府県設計",
    "CHANGELOG.md": "変更履歴（生）",
    "CLAUDE.md": "恒久ルール",
    "DESIGN_HANDOFF.md": "デザイン引き継ぎ手順",
    "server/README.md": "サーバー運用手順",
}


def sh(cmd: str) -> str:
    return subprocess.run(cmd, cwd=REPO, capture_output=True, text=True,
                          shell=True, encoding="utf-8", errors="replace").stdout.strip()


def version() -> str:
    m = re.search(r"^version:\s*(\S+)", (REPO / "pubspec.yaml").read_text(encoding="utf-8"), re.M)
    return f"beta{m.group(1)}" if m else "unknown"


def stamp() -> str:
    return datetime.now().strftime("%Y-%m-%d %H:%M")


def fm(title: str, tags: list[str]) -> str:
    """Obsidian frontmatter。source は自動生成の証跡。"""
    return (
        "---\n"
        f"title: {title}\n"
        f"updated: {stamp()}\n"
        f"tags: [{', '.join(tags)}]\n"
        "source: auto-generated by tool/obsidian_sync.py\n"
        "---\n\n"
        "> [!info] 自動同期ノート\n"
        "> このノートはリポジトリから自動生成されています。編集はリポジトリ側で行ってください。\n\n"
    )


def sync_docs() -> list[str]:
    (DEST / "docs").mkdir(parents=True, exist_ok=True)
    synced = []
    for src_name, label in DOCS.items():
        src = REPO / src_name
        if not src.exists():
            continue
        body = src.read_text(encoding="utf-8")
        # server/README.md のようなサブディレクトリ配下も1ファイルへ平坦化する
        slug = src_name.replace(".md", "").lower().replace("_", "-").replace("/", "-")
        out = DEST / "docs" / f"{slug}.md"
        out.write_text(fm(label, ["ble-encounter-app", "docs"]) + body, encoding="utf-8")
        synced.append(f"docs/{slug}|{label}")
    return synced


def sync_history():
    log = sh('git log --pretty=format:"%ad|%h|%s" --date=short')
    lines = [fm("バージョン履歴", ["ble-encounter-app", "history"]),
             "# バージョン履歴\n",
             f"現行: **{version()}** / コミット総数: {len(log.splitlines())}\n"]
    cur_month = ""
    for line in log.splitlines():
        parts = line.split("|", 2)
        if len(parts) < 3:
            continue
        date, sha, subj = parts
        month = date[:7]
        if month != cur_month:
            cur_month = month
            lines.append(f"\n## {month}\n")
        # betaコミットは太字で強調（リリース点が一目で分かる）
        if subj.startswith("beta"):
            lines.append(f"- **{date}** `{sha}` **{subj}**")
        else:
            lines.append(f"- {date} `{sha}` {subj}")
    lines.append("\n\n関連: [[index]]")
    (DEST / "history.md").write_text("\n".join(lines), encoding="utf-8")


def sync_index(synced: list[str]):
    tests = sh("git ls-files test/*.dart").splitlines()
    tools = sh("git ls-files tool/*").splitlines()
    loc = sh('git ls-files "lib/*.dart"').splitlines()
    body = [
        fm("BLE Encounter App", ["ble-encounter-app", "project", "moc"]),
        "# はじめましてこんにちは（BLE Encounter App）\n",
        "> Bluetoothですれ違った人との出会いを楽しむコミュニティゲーム\n",
        f"**現行バージョン:** {version()}　**最終同期:** {stamp()}\n",
        "## クイックリンク\n",
    ]
    for s in synced:
        path, label = s.split("|")
        body.append(f"- [[{path.split('/')[-1]}|{label}]]")
    body += [
        "- [[history|バージョン履歴]]",
        "- [[sessions|作業ログ]]（sessions/ 配下）",
        "\n## 絶対維持事項（破壊禁止）\n",
        "- GPS不使用（BLEのみ）／BLE中心設計／匿名性",
        "- 気配演出（すれ違い直後は相手を隠す）／開門システム（朝9・昼12・夜21）",
        "- 回転トークン方式（永続IDを電波に流さない）",
        "- プライバシー保護（数値の抽象化・正確な時刻や場所を出さない）",
        "\n## 現状サマリー\n",
        f"- Dartソース: {len(loc)} ファイル",
        f"- 回帰テスト: {len(tests)} ファイル（`flutter test`）",
        f"- 自動化ツール: {len(tools)} 本（`tool/`）",
        "\n## 開発環境\n",
        "```",
        f"リポジトリ: {REPO}",
        "GitHub: https://github.com/miyamaaaaasa/ble-encounter-app",
        "Supabase: fscchyuzjbnylofptsou (HazimemasiteKonnitiwa Project)",
        "署名鍵: android/keystore/release.jks（gitignore・要バックアップ）",
        "```",
        "\n## よく使うコマンド\n",
        "```powershell",
        "pwsh tool/dev.ps1 check      # 静的解析",
        "pwsh tool/dev.ps1 test       # 回帰テスト",
        "pwsh tool/dev.ps1 cycle      # test→bump→build→deploy→logs",
        "pwsh tool/dev.ps1 release    # リリース一括（commit/pushまで）",
        "bash  tool/qa_smoke.sh       # 無人スモークQA",
        "python tool/obsidian_sync.py # このvaultへ同期",
        "```",
        "\n関連: [[ble-encounter-app|旧プロジェクトノート]] / [[auto-git-workflow]]",
    ]
    (DEST / "index.md").write_text("\n".join(body), encoding="utf-8")


def add_session(summary: str):
    d = DEST / "sessions"
    d.mkdir(parents=True, exist_ok=True)
    today = datetime.now().strftime("%Y-%m-%d")
    f = d / f"{today}.md"
    # 直近コミット（今日の分）を自動添付
    todays = sh(f'git log --since="{today} 00:00" --pretty=format:"- `%h` %s"')
    entry = [f"\n## {stamp()} — {version()}\n", summary.strip(), ""]
    if todays:
        entry += ["\n### この日のコミット\n", todays, ""]
    if f.exists():
        f.write_text(f.read_text(encoding="utf-8") + "\n".join(entry), encoding="utf-8")
    else:
        head = fm(f"作業ログ {today}", ["ble-encounter-app", "session-log"])
        f.write_text(head + f"# 作業ログ {today}\n" + "\n".join(entry) +
                     "\n\n関連: [[index]] / [[history]]", encoding="utf-8")
    print(f"  session -> sessions/{today}.md")


def main() -> int:
    if not VAULT.exists():
        print(f"NG: vault が見つかりません: {VAULT}")
        return 1
    DEST.mkdir(parents=True, exist_ok=True)
    print("== Obsidian sync ==")
    synced = sync_docs()
    print(f"  docs: {len(synced)} 件")
    sync_history()
    print("  history.md")
    sync_index(synced)
    print("  index.md")
    if "--session" in sys.argv:
        i = sys.argv.index("--session")
        if i + 1 < len(sys.argv):
            add_session(sys.argv[i + 1])
    print(f"== done -> {DEST}")
    return 0


if __name__ == "__main__":
    sys.exit(main())
